### PR TITLE
[WIP] Rename File of running instance

### PR DESCRIPTION
**Pull request by vito-c**
This is a bit of a work in progress but what it does is allow you to rename the file of the running instance. It uses the browser's local storage
to keep track of the file being edited. It maps the "url" to the file on your local system.

This PR is not quite ready but I wanted to share it with you to see my progress.

Steps to use:
1. Open a page with a text editor and activate neovim
2. Open the developer tools and select the firenvim plugin iframe
3. Type `window.renameFile("foo.txt")`
4. Make some changes to the file and save the buffer
5. You can view the current file by typing `:echo @%`
6. Reload the page

### CODE REVIEW

**Review by glacambre — COMMENTED** [review]
If I'm understanding this correctly, this maps the auto-generaated filename Firenvim creates to another, user-specified one if it exists. This is different from what I had in mind [here](https://github.com/glacambre/firenvim/issues/1081#issuecomment-874966900) (not necessarily a bad thing!) and it makes me wonder what your use case is exactly - why you need to change the filename and why doing this manually on a textarea-basis makes sense. Could you expand on that ? :)

**Comment by vito-c** [comment]
Sure thing. When I was playing with firenvim there were a  few sites that let you choose your language via a drop ydown. Firenvim wasn't able to correctly identify the language I picked. As a  result I would have to do `set ft=mylang`. I would have to do it every time I  can back to the page. I got tired of doing this so I wanted  a  way to set the textarea  to a custom name.

**Comment by glacambre** [comment]
I see. This can already be achieved with something like `au BufRead github.com* set filetype=md` (there's an example [here](https://github.com/glacambre/firenvim#using-different-settings-depending-on-the-pageelement-being-edited). Is there a situation where you can't use autocommands?

**Comment by vito-c** [comment]
> I see. This can already be achieved with something like au BufRead github.com* set filetype=md (there's an example here. Is there a situation where you can't use autocommands?

That lets you change the filetype but not the name. So for the situtations that I want a scala worksheet this won't work becuase the way metals work is it uses `.scala` for `filetype=scala` but then also has `foo.worksheet.sc` which is the same filetype but requires the name to have worksheet in it.

**Comment by glacambre** [comment]
Does something like `au BufRead the-domain-where-there-are-scala-worksheets.com* file foo.worksheet.sc | :e!` work for this?

**Comment by glacambre** [comment]
Closed by https://github.com/glacambre/firenvim/pull/1138 . @vito-c thanks a lot for taking a stab at implementing this, and sorry your code didn't make it into firenvim. Feel free to tackle any other issue still open ;).

**Comment by vito-c** [comment]
Thank you! Sorry I wasn’t able to spend more time on it

**Pull request closed without merging**
