### PR TITLE
fixes installing fire nvim on brave

### LINKED ISSUE #773: Making Brave Work
- OS Version: linux x86-64 (ubuntu, 19.10)
- Browser Version: Brave-Browser: 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit)
- Browser Addon Version: 0.1.32
- Neovim Plugin Version: 0.1.32
- What I tried to do: Add some serious coconut oil.
- What happened:  Oil was added and brave worked!!!

But Seriously, this is what happened.  I am trying to make brave work and was
unable to do so.  Kept saying that "Neovim died", Luckily I was failing on
twitch and a nice viewer, named Flame_Kasai, told me to check the configs.

Therefore I did the following things:
0. Ensured that i installed everything: `nvim --headless "+call firenvim#install(69) | q"`

```
Installed native manifest for chromium.
Installed native manifest for opera.
Installed native manifest for brave.
Installed native manifest for vivaldi.
Aborting installation for chrome-canary. Chrome Canary doesn't exist on Linux
Installed native manifest for chrome.
Installed native manifest for firefox.
```

1. $HOME/.config/chromium/NativeMessagingHosts and ensured its identical to
   google-chrome's configuration.  It was.

2. firenvim still didn't work

3. Then It was mentioned, (flame above), that there is a BraveSoftware folder.
   I went into it and found another NativeMessagingHosts folder and copied the
   config from chromium to it (located here:
   $HOME/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts).

4. ...

5. After that firenvim worked like a charm!! (and profit)

-----
After looking at the autoload script it does look like it mostly gets brave
correct.  My assumption is that the install does not put it in the correct
brave location.

This looks mostly correct.  It just seems to be missing `Brave-Browser` folder.

[AutoLoad](https://github.com/glacambre/firenvim/blob/master/autoload/firenvim.vim#L188)

----
BTW, I am typing this issue up using firenvim and its straight fire.

### PR DESCRIPTION
**Pull request by bryall**
fixes #773

confirmed linux and mac paths (do not have a machine to test windows)

### CODE REVIEW

**Comment by glacambre** [comment]
Thanks for taking the time to fix this! I'm curious, did you find these paths somewhere in Brave's documentation? I'm wondering because as said in https://github.com/glacambre/firenvim/issues/773#issuecomment-724908899 , brave has worked for some people before, so either the paths changed or they're only wrong on some OSes and not others.

**Comment by bryall** [comment]
It was using the chrome data directory to write the manifest for the brave browser. this should have never worked unless you copied the file manually like Prime and I did

I could not find official documentation, just posts stating these paths

**Comment by glacambre** [comment]
According to brave contributors, using Chrome's directory is [the correct thing to do](https://github.com/brave/brave-browser/issues/5074#issuecomment-657231128) (at least on OSX?). Since https://github.com/glacambre/firenvim/issues/144 used Firenvim on Brave on OSX without reporting any issues I'd prefer it if your PR only changed the path for Linux. Do you want me to perform this change or would you rather do it yourself?

**Comment by glacambre** [comment]
Ugh, the references to the native manifest I found in Brave's source code indicate that Chrome's directory should also be used on linux:

https://github.com/brave/brave-core/blob/bbbf3b2e65b440a732f4199e598461a65775ff8f/app/brave_main_delegate.cc#L134-L161

But this is obviously wrong since it didn't work for you or ThePrimeagen… I'm wondering, how did you install Brave? Through your distro's package manager?

**Comment by bryall** [comment]
i installed through the brave [download page](https://brave.com/linux/#release-channel-installation) (using Ubuntu 20.04)

I can do some more tracing tomorrow to see what is going on, something must have changed since the original code

**Comment by glacambre** [comment]
Ok, so on OSX it's chrome's directory but on Linux it's regular XDG: https://github.com/brave/brave-core/blob/6a02303906a4a5d7c3d57f4cef29204593f9e40b/chromium_src/chrome/common/chrome_paths_linux.cc#L16-L28 . Please make sure that your PR only changes paths for Linux and I'll be happy to merge it :)

**Comment by glacambre** [comment]
Again, thank you for taking the time to fix this! :)

**Comment by tristan957** [comment]
I don't think the solution is totally right for Linux.

If you look at the chromium source code linked above it is checking for the existence of the env var XDG_CONFIG_HOME which isn't necessarily ~/.config. If XDG_CONFIG_HOME isn't set, I would bet the function just defaults to ~/.config which is following the XDG spec to a tee.

XDG spec says if XDG_CONFIG_HOME isn't set default to ~/.config.

I am no viml god, but what you need to do is something like

```
if $XDG_CONFIG_HOME set:
  build_path([$XDG_CONFIG_HOME, 'BraveSoftware', ...])
else
  build_path[WHAT YOU HAVE CURRENTLY])

**Comment by glacambre** [comment]
Thanks for pointing this out. I assumed that brave was "lying" about the path actually following XDG and that it'd only return the default path, as [Chrome's documentation](https://developer.chrome.com/apps/nativeMessaging#native-messaging-host-location-nix) explictly states that `~/.config` should be used.
But I dug a little deeper and it looks like [GetXDGDirectory](https://chromium.googlesource.com/chromium/src.git/+/master/base/nix/xdg_util.cc#46) does [lookup](https://chromium.googlesource.com/chromium/src.git/+/master/base/third_party/xdg_user_dirs/xdg_user_dir_lookup.cc#201) XDG variables.
@tristan957 your code suggestion looks correct to me - do you want to submit a PR?

**Comment by tristan957** [comment]
Ha. Yeah I'll see if I can figure out some viml.

**Pull request merged**
