### PR TITLE
Map out a function for tweaking site configs

### LINKED ISSUE #267: `add()`/`remove()` functions to make tweaking config easier
It might be worth having `add()`/`remove()` functions so that a default array can be maintained in the plugin and config files can just tweak to users' preferences. Having users set the entire array in their rc files for something that potentially has a lot of values is starting to get messy. Per-site configs could also be shared easier if each one was self contained.

Just brainstorming here, but maybe an adder that that accepted a site, selector, and optional priority arguments, and a remover that just took the site...

```vim
" Only catch some textareas on example.com
call firenvim#add_site_config('example.com, '.class textarea')

" Disables on riot.im (no selector)
call firenvim#add_site_config('riot.im')
```

_Originally posted by @alerque in https://github.com/glacambre/firenvim/issues/264#issuecomment-558550442_

### LINKED ISSUE #268: Add new Firenvim filetype & include domain-aware syntax highlighting
I've been using setting the `markdown` filetype for _most_ sites that I use Firenvim on including ones that are not actually markdown. Whatsapp web and Slack for example have bastardized Markdown-ish syntax that isn't actually Markdown.

As I use Firenvim on more and more sites I'm starting to run into more cases where some unique filetype handling and syntax rules would be useful.

Off the top of my head my suggestion is to default all Firenvim files to a new filetype `firenvim` by default unless otherwise requested by the user (see #267 for a related improvement), and bundle a syntax file for that filetype that uses the buffer name to add per-site syntax highlighting. I would implement that by first parsing out the domain, then checking if a setup function for that domain exists and calling it if it does.

Besides being able to handle some common cases out of the box, this would provide the framework for users to override Firenvim's defaults and extend the behavior of vim on a given domain just a bit easier than it is now.

### PR DESCRIPTION
**Pull request by alerque**
This is my attempts to come up with something that makes Firenvim easier to configure and use on a per-site basis without making user's init.rc files look like spaghetti and while allowing Firenvim to evolve without breaking configs.

Fixes #267 and fixes #268 (or will by the time it comes out of draft mode).

### CODE REVIEW

**Comment by alerque** [comment]
Here's an example of how this works for now:

```vim
if exists('g:started_by_firenvim')
	call firenvim#configure_site('github.com', 'textarea', 1, 'markdown')
	call firenvim#configure_site('gitlab.com', 'textarea', 1, 'markdown')
	call firenvim#configure_site('gitlab.alerque..com', 'textarea', 1, 'pandoc')
	call firenvim#configure_site('*stackoverflow.com', '')
	call firenvim#configure_site('*.stackexchange.com', '')
endif
```

Calling `configure_sites()` with N args:

* **0**: Resets to the default plugin configuration
* **1**: Clears any settings for a domain
* **2**: Sets a selector for a domain, setting `''` basically blacklists
* **3**: ...plus a non-default priority
* **4**: ...plus a custom filetype

Obviously this has some serious problems, such as only being able to set one configuration per domain, but I had to start experimenting somewhere. Feedback is appreciated.

**Comment by alerque** [comment]
About the time I started adding the fourth optional argument I started running into issues with my own personal config. Testing that all the scenarios work becomes tricky. If it surprised _me_ at the time of implementating it, I think more specific functions with fixed sets of required arguments might be better. I'll work on amending this in that direction.

I did think of passing dictionaries, but if that barely helps over just setting them manually:

```vim
let g:firenvim_config['localSettings']['example.com'] = { .... }
```

I was hoping for something a bit more elegant. A function just to alias a call to setting a dictionary key is not a huge step forward.

**Comment by alerque** [comment]
It's hard to get away from requiring verbose input without variable arguments. I messed with it a bit and couldn't come up with something I liked that didn't use optional arguments. That being said I did try setting up some other functions that could make the whole experience less surprising.

```vim
if exists('g:started_by_firenvim')
  " call firenvim#reset_sites() " to be used if people want to start with no config instead of defaults
  call firenvim#default_sites() " optional for end users, but maybe useful
  call firenvim#configure_site('example.com', 'textarea.large')
  call firenvim#configure_site('gitlab.com', 'textarea', 1, 'markdown')
  call firenvim#configure_site('gitlab.alerque..com', 'textarea', 1, 'pandoc')
  call firenvim#configure_site_filetype('web.whatsapp.com', 'markdown') " only set &ft, not other configs
  call firenvim#uncnofigure_site('riot.im) " say we included special rules for a site
  call firenvim#disable_site('*stackoverflow.com')
endif
```

This still doesn't address how to handle multiple selectors per site (which dictionaries do make easier) but I think tweaking from here to use `add_site_selector()` /`remove_site_selector()` would simplify the remaining cases.

**Comment by glacambre** [comment]
The more I think about it the more I tell myself that people who want a more concise way of configuring firenvim could just do this
```vim
let g:fc = {}
let g:fc['github.com']  = { 'selector': 'textarea', 'priority': 1, 'filetype': 'markdown' }
let g:fc['example.org'] = { 'selector': '' }
let g:firenvim_config = { 'localSettings': g:fc }
```

It looks concise and flexible enough to me. What do you think?

**Pull request closed without merging**
