### PR TITLE
Webgl rewrite

### LINKED ISSUE #347: Rewrite the renderer
The current renderer is pretty slow and is partially responsible for Firenvim's latency problem. This is because it uses the DOM, which isn't intended for this kind of use. Using the DOM made a lot of sense at the beginning of Firenvim because it reduced the amount of things to learn, however, now that I know most of what you need to know in order to write a Neovim GUI, it would make sense to rewrite it with performance in mind.

The new renderer should:
1) Support all current Neovim UI extensions
2) Be easy to maintain
3) Be fast

Supporting all current Neovim UI extensions from the start is important because it helps [avoid bugs](https://github.com/neovim/neovim/issues/11646#issuecomment-570074095) and will create part of the groundwork necessary for new, yet-to-come ui extensions. Easy maintenance is important because I have less and less motivation to work on Firenvim, I should thus reduce the maintenance burden for myself and make it easy for new contributors to hack on Firenvim. Being fast is the whole point of the rewrite and the only reason it would be ok to sacrifice speed is that an UI extension can't be implemented in an efficient way or that it would increase the maintenance burden. 

There are multiple technologies that could satisfy our needs:
- The Canvas2D API
- WebGL
- WebGPU

The canvas API is probably the easiest API to work with but also the slowest but it might be enough to reach 60fps (you can't go higher in a browser). An important point is that it has text-rendering functions (e.g. [fillText](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillText)), this would help a lot during development.
The WebGL approach would be more complex but provide more control. It doesn't provide text-rendering functions and thus would probably require to hack something by rendering text with Canvas2D first and then caching the glyphs and reusing the pixels in a WebGL context.
WebGPU isn't out yet but seems to be "WebGL but modeled on Vulkan rather than OpenGL". It would probably suffer from the same issues we have with WebGL.

[Neovim-e](https://github.com/coolwanglu/neovim-e) uses Canvas2D.
[Nyaovim](https://github.com/rhysd/NyaoVim) says it uses a canvas but I couldn't find the code.
[OniVim 1](https://github.com/onivim/oni) uses WebGL.
[Veonim](https://github.com/veonim/veonim) uses WebGL.
[Vv](https://github.com/vv-vim/vv) uses Canvas2D.

Overall, it seems that even though the Canvas approach seems simpler, the more polished UIs chose to use WebGL. This might indicate that Canvas2D isn't good enough.

One last thing to keep in mind is that some users probably use canvas-disabling extensions. Since Firenvim renders things in its own iframe it might not be affected, we need to figure out how these extension work and whether we'll need to implement a fallback to the DOM renderer or not.

I can probably use Pavel Fatin's excellent [typometer](https://pavelfatin.com/typometer/) to measure how fast the new renderer is compared to the old one.

### LINKED ISSUE #471: Background of double-width characters is single-width
Thank you for the most useful addon ever!

However, it seems that background of double-width characters is single-width.

- OS Version: mac x86-64
- Browser Version: Google Inc. Chrome 80.0.3987.132
- Browser Addon Version: 0.1.21
- Neovim Plugin Version: 0.1.21
- What I tried to do: Input some double-width characters and enter visual-line mode
- What happened:
screenshot

### PR DESCRIPTION
**Pull request by glacambre**
Should be all done now. Opening a PR to let people try it out.

Closes #347.
Closes #471.

### CODE REVIEW

**Comment by alerque** [comment]
Cool to see this coming! I haven't gotten to test drive it yet, but looking forward to the expected improvements it should bring.

**Comment by glacambre** [comment]
I think this is ready, for real this time! Please try the new renderer out and let me know what you think/if you find bugs/have suggestions.

To try Firenvim on Firefox:
- Download [this file](https://github.com/glacambre/firenvim/files/5395968/firenvim-0.1.31.zip).
- Go to `about:config`, dismiss the warning if needed.
- In the search bar, search for `xpinstall.signatures.required` and set it to false.
- Go to about:addons.
- Uninstall Firenvim.
- Click on the cog icon.
- Select `install addon from file`.
- Select the file you downloaded earlier.

On Chrome-based browsers:
- Download [this file](https://github.com/glacambre/firenvim/files/5395974/chrome.zip) file.
- Unzip it in an empty directory.
- Go to `chrome://extensions`.
- Remove Firenvim.
- Enable developer mode.
- Select `Load unpacked`.
- Select the directory where you unzipped `chrome.zip`.

Please try them on websites you usually use (but remember to switch back to the version from the chrome/firefox addon stores as installing addons from files means the addons do not receive updates).

**Comment by NilsIrl** [comment]
This has comment has been written on the new renderer.

You can also install the addon from `about:debugging`.

Visible changes:
* The frame seems a bit blurry and less sharp
* The frame was moving upward and downward by 1 pixel at the beginning, although I'm not longer able to reproduce it.
* I can't remember how it behaves on the old renderer, but now visible selection with the mouse waits for the left click to be released before selecting the text

Anyway, apart from this I haven't noticed anything (I haven't used the new renderer a lot (I couldn't help myself to try it out)).

**Comment by glacambre** [comment]
@NilsIrl I hadn't even thought about testing firenvim with a different zoom level, I'll see if I can do something about that. The frame moving around is probably a bug that also exists in the old renderer and mouse behavior hasn't changed between the two renderers. Thanks a lot for your help!

**Comment by glacambre** [comment]
@maxigaz could you describe your airline config here? I inferred that you had `g:airline_powerline_fonts` set to 1 but what's your theme/have you configured anything else? Have you had to configure your `guifont`?

**Comment by maxigaz** [comment]
> @maxigaz could you describe your airline config here? I inferred that you had `g:airline_powerline_fonts` set to 1 but what's your theme/have you configured anything else?

Here’s all the settings I have for Airline:

```vim
let g:airline_powerline_fonts = 1
let g:airline_theme='solarized'
let g:airline#extensions#wordcount#filetypes='markdown'
let g:airline#extensions#ale#enabled = 1
let g:airline#extensions#whitespace#checks = [ 'indent', 'mixed-indent-file', 'conflicts' ]
```

> Have you had to configure your `guifont`?

Yes, now that you mention it, I remember I had to put the following in my `init.vim` as well to customise the appearance in Firenvim:

```vim
function! s:IsFirenvimActive(event) abort
  if !exists('*nvim_get_chan_info')
    return 0
  endif
  let l:ui = nvim_get_chan_info(a:event.chan)
  return has_key(l:ui, 'client') && has_key(l:ui.client, 'name') &&
      \ l:ui.client.name =~? 'Firenvim'
endfunction

function! OnUIEnter(event) abort
  if s:IsFirenvimActive(a:event)
     set lines=30 " This comes BEFORE guifont
     set guifont=Hack:h12
     hi! Normal guibg=#002b36
     nnoremap <Esc><Esc> :call firenvim#focus_page()<CR>
  endif
endfunction
autocmd UIEnter * call OnUIEnter(deepcopy(v:event))
```

**Comment by glacambre** [comment]
What neovim version are you using? My powerline symbols do not have the same highlighting as yours:
Screen Shot 2020-10-18 at 16 25 56

**Comment by maxigaz** [comment]
> What neovim version are you using?

Neovim v0.4.4.

> My powerline symbols do not have the same highlighting as yours:
> Screen Shot 2020-10-18 at 16 25 56
> 
> Edit: firenvim is unfocused in my screenshot so the colors are a bit faded, but when firenvim is focused everything is the same color as in yours except for the powerline symbols.

I think I know why. I also have the following in my `init.vim`:

```vim
set termguicolors
```

If I uncomment it in another Neovim instance and restart the instance spawned by Firenvim twice (not sure why it has to be done twice, but anyway…), the Powerline symbols look out of place here, too, like on your screenshot.

**Comment by glacambre** [comment]
@maxigaz Thanks, with `termguicolors` I can reproduce your theme. This looks like an issue with vim-airline, I've opened https://github.com/vim-airline/vim-airline/issues/2261 to discuss it.

>restart the instance spawned by Firenvim twice (not sure why it has to be done twice, but anyway…)

This is because Firenvim pre-loads a neovim instance for performance. So once you killed your current instance, the next one still has the previous configuration loaded and you need to kill it too. I agree that it's not great UX but I can't think of alternatives.

**Comment by glacambre** [comment]
Note to self: add support for the `linespace` setting.

**Comment by jameswalmsley** [comment]
Is this going to be merged soon? Looks awesome :D

**Comment by glacambre** [comment]
On 12/30/20 2:30 PM, James Walmsley wrote:
> Is this going to be merged soon? Looks awesome :D

I hope so, I'm currently trying to fix some issues upstream to make 
working on Firenvim easier :).

**Comment by jameswalmsley** [comment]
Cool.
I'll try to patch it in manually and give it some testing.

Thanks for your awesome work.

**Comment by BrunoGomesCoelho** [comment]
I've been trying the uploaded file version and it works a lot faster, thanks for the awesome addon!

I did try to build the version from the webgl_rewrite branch directly to test (not sure if it's been more recently updated than the file) but I had errors while building (and no errors for the master branch);

If there's meant to be errors I can test the latest version whenever they're fixed, if there aren't I'll stick with the file version since it's probably a mistake on my side.

**Comment by glacambre** [comment]
On 1/3/21 4:23 AM, Bruno Gomes Coelho wrote:
> I've been trying the uploaded file version and it works a lot faster, 
> thanks for the awesome addon!

That's great to hear, thanks for the feedback :).
> 
> I did try to build the version from the webgl_rewrite branch directly to 
> test (not sure if it's been more recently updated than the file) but I 
> had errors while building (and no errors for the master branch);

You could try `"$(npm bin)/webpack" --env=firefox` or `"$(npm 
bin)/webpack" --env=chrome` followed by `npm run pack` instead of `npm 
run build`, this should skip a few checks. If that doesn't work I guess 
you'll have to stay on the old version until I finish this PR :).

**Comment by BrunoGomesCoelho** [comment]
Thanks for the quick reply, your suggestion worked!

**Pull request merged**
