### PR TITLE
Correctly detect Monaco editor in GitLab Web IDE

### PR DESCRIPTION
**Pull request by thomaswucher**
GitLab seems to use a sligtly modified Monaco editor in the GitLab Web IDE. With this minor change firenvim works well within GitLab Web IDE.

### CODE REVIEW

**Comment by glacambre** [comment]
This doesn't seem to be enough to make Firenvim work in Gitlab's IDE on my end. What browser are you using?

**Comment by glacambre** [comment]
Mh, it indeed works in Chrome. Seems to be a CSP issue in Firefox, kind of like https://github.com/glacambre/firenvim/issues/145 .

No reason not to merge then, thank you for taking the time to debug this and find a fix! :)

**Comment by thomaswucher** [comment]
Thanks for testing and merging this so quickly! I actually tested it in Firefox 76.0.1 on Arch Linux, so I'm unsure why it doesn't work for you.

**Comment by xerus2000** [comment]
Gitlab Web IDE also doesn't work for me using Firenvim 0.1.30 in Firefox on KDE Neon (Ubuntu 18). Clicking the textbox renders it unclickable without a firenvim window appearing, sort of like an invisible overlay. Plugin version in Neovim is also up to date.

**Pull request merged**
