### PR TITLE
Implement firenvim#press_keys()

### PR DESCRIPTION
**Pull request by glacambre**

### CODE REVIEW

**Comment by justinmk** [comment]
`feedkeys` would be somewhat more intuitive for Vim users maybe.

**Comment by glacambre** [comment]
I can see your point but at the same time this would probably be slightly confusing as `press_keys` doesn't actually behave the same way `feedkey` does: running `firenvim#press_keys("a")` won't actually append `a` to the input field's content, it will just trigger a fake key event on the input field that the input field might decide to react to (e.g. if `a` is supposed to do something special).

This makes me realize that `press_keys` is probably a bad name. Perhaps `simulate_keypress` or `trigger_keyevent` would be better. I should probably also use the word `feedkeys` in the documentation to make it easy to find for users who grep for it.

**Comment by xerus2000** [comment]
Is this option documented somewhere?

**Comment by glacambre** [comment]
On 2020-06-17 22:51, Janek wrote:
> Is this option documented somewhere?

Yes, right here: 
https://github.com/glacambre/firenvim#interacting-with-the-page :)

**Pull request merged**
