### PR TITLE
Added installation instructions for lazy.nvim

### PR DESCRIPTION
**Pull request by hankertrix**
I also included how to lazy load firenvim using lazy.nvim as well.

### CODE REVIEW

**Comment by glacambre** [comment]
This is great, thanks a lot for taking the time to do this! Could you squash these two commits together? You can do that by running `git rebase HEAD^^ -i` and replacing the first word on the line of commit `70cd641` with `squash`. This will then launch your editor to edit the commit message of the squashed commit, where you should remove the `Changed the number on the third step from 2 to 3.` line.

**Comment by hankertrix** [comment]
Done! Squashed the commit as you requested. Thanks for the instructions, it helped me a lot!

**Comment by glacambre** [comment]
Unfortunately it looks like something went wrong: instead of containing one squashed commit, your PR now contains four commits: the original two, a merge commit and the squashed commit. I could be wrong, but I suspect this might be due to using Repl.it to perform your changes (I wrongly assumed that you would perform the steps from the command line).

Unfortunately I can't fix this myself because the changes are on master. In general, it's better to submit your pull requests from a new branch, which you can create by running `git checkout -b <name_of_the_new_branch>` in the terminal before performing any change. Performing your changes on a new branch enables the maintainers to help fix issues in your pull requests.

We could either try to fix this pull request or create a new one, as you prefer. If you want to fix this pull request, you should run `git rebase -i HEAD^^^` and remove the lines for commits `202181c`, `70cd641` and `8891aed`. Once the commits are removed, you can push your branch with `git push --force`.

If you prefer to open a new pull request, I would recommend running the following commands:
```
git checkout -b my-new-branch d1909c7 # This creates a new branch that does not contain your commits
git cherry-pick a19fde8 # This adds the squashed commit to your new branch
git push # This pushes the new branch to GitHub
```
And then, use the Github web interface to open a new pull request. In theory, this just means visiting https://github.com/hankertrix/firenvim - you should see a button offering to create a new pull request :).

**Comment by alerque** [comment]
@glacambre You know you can merge this with GitHub's interface and have it squash them all at merge time, right? You can even update the message to your liking in the process.

**Comment by glacambre** [comment]
@alerque Ha, no, I didn't know that the commit message could be edited during a squash+merge operation (I never dared pressing the button :D ). Thanks a lot for the tip :).

@hankertrix You can ignore all of my previous messages. Sorry for making you do extra work!

**Comment by hankertrix** [comment]
Ah no worries! Now I know I can’t squash commits using Repl.it. I was not at my computer so I used Repl.it’s web IDE to use Git from the shell to squash the commits.

**Pull request merged**
