### PR TITLE
Add firenvim#focus_page()

### LINKED ISSUE #236: Command API for changing focus from the neovim iframe
Thanks for this great project!
After I start editing a textarea in the neovim iframe, is there a way to focus back on the original page using a keybinding?
I can do this by clicking with the mouse outside the iframe.

Thanks!

### PR DESCRIPTION
**Pull request by glacambre**
Fixes #236

### CODE REVIEW

**Comment by infokiller** [comment]
Thanks for tackling this so quickly!
If I understand this implementation correctly, this requires the user to map a key in init.vim which then uses the plugin to change focus.
I'm wondering if it makes more sense to use [commands](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands) and directly capture the keybinding in the extension?

**Comment by alerque** [comment]
Personally I'd much rather map something in my init.rc file (which is easy to version & sync) than try to set it and keep it in my Firefox profile (which is not). I suspect among people nerdy enough to be using vim in their browser in the first place I'm probably not alone.

**Comment by infokiller** [comment]
I agree, but using the commands API lets you use almost any keybinding.

**Comment by alerque** [comment]
If it would let me use <kbd>Ctrl</kbd><kbd>W</kbd> then sign me up ;-)

**Comment by infokiller** [comment]
Yes, I wanted to experiment with commands anyway to fix the issue with `Ctrl-w` and other keybindings. We may be able to define a command for each of these keys and overcome the current limitation.
I will try to play with this a bit.

**Comment by glacambre** [comment]
I would be willing to make it possible to do this from both neovim and the commands API, but the problem with the commands API is that keyboard events bound to commands are treated as regular events, so if the application uses `preventDefault`/`stopImmediatePropagation`, the command isn't triggered. Firenvim needs to use preventDefault and stopImmediatePropagation on every event to prevent default keybindings from messing with neovim.

An obvious solution would be to retrieve the list of existing commands and not call preventDefault if the event matches a keybinding used by a command, but if we do this I want users to be able to decide whether their keybindings should be registered by neovim or their browser. So this requires more work than what I've done in this PR and will have to come later :)

**Pull request merged**
