### PR TITLE
Huge refactor

### PR DESCRIPTION
**Pull request by glacambre**
This is the groundwork for thunderbird support.

### CODE REVIEW

**Comment by molleweide** [comment]
I am a git beginner if I may say so and I was wondering why you are not using Conventional Commit message here? I'm just curious because I am really trying to up my git game and learn from all of you neovim core devs.

**Comment by alerque** [comment]
You're not *quite* alone, some of us to follow along with commit history, especially since the commit long turns up when we update our VIM plugins. Also the hygiene of using consistent commits and sticking to separation of concerns (such as not mixing style/feature/fix/refactor in a single commit) has been one of the best things I've done for the project I work on alone. They have gotten so much more manageable now that I can leave branches alone for a while and pick them up again without loosing a bunch of brain time trying to figure out where I was, or actually understand the output of `git blame` to quickly hit on where I need to go when troublesome edge cases manifest later.

**Comment by molleweide** [comment]
I just learnt about interactive rebasing and `git add --patch` this weekend. I feel like I have been reborn LOL.

**Comment by alerque** [comment]
Wait until you learn to manipulate `git add --patach` inside your editor (such as `vim-gitgutter` and others can do to stage the hunk under the cursor), then combine that with `git revise` to stuff the bits you staged into an old commit!

**Comment by molleweide** [comment]
Woaw dude!! I'll check em out.

**Comment by alerque** [comment]
No [that](https://cdn.shopify.com/s/files/1/1152/3264/t/25/assets/neat-people.png?v=14828103136703394800) is not me, although I do see the resemblance. Beards for the win. I do wish I had an Ergodox EZ, it looks like a great product. I'm a current user of a Kinesis Advantage and Keyboardio Atreus (with a Model 100 on pre-order), but I frequently wonder if I should have tried an Ergodox EZ along the way. I actually saw the crowdfunding campain for it but was flat broke at the time. I'm a big fan of ortholinear layouts — and the split design, lots of modifier options, open source firmware, etc. check off lots of the right boxes for me. If @jackhumbert or whoever is behind the ergodox wants to sponsor me for a piece of kit I'd be happy to give my very honest review and pose with my beard for their home page.

**Comment by molleweide** [comment]
> No [that](https://cdn.shopify.com/s/files/1/1152/3264/t/25/assets/neat-people.png?v=14828103136703394800) is not me, alth
No not that guy. I recall your face from the user stories segment, but now
since you say no I am not going to try to convice you that you have one haha.

You should see these ones.
https://southpawdesign.net/products/centromere-mini-group-buy?variant=31652187537468

But the coolest thing is this project called kmonad which allows you to create qmk
style layouts on your laptop. For example, I have the centromere 3by5 layout on my
macbook pro now with 10 different layers and homerow modifiers so that i never have
to leave homerow ever etc. It has allowed me to have the exact same layout on my laptop
as on my mechanical keyboards which is the most surreal thing ever.

**Pull request merged**
